#!/usr/bin/env bash
set -euo pipefail

# 1. Detect OneDrive path based on OS
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS: OneDrive personal sync location
    # Standard users cannot reliably chmod files inside ~/Library/CloudStorage
    # so we check both common locations.
    ONEDRIVE_SSH="$HOME/Library/CloudStorage/OneDrive-Personal/ssh"
    if [ ! -d "$ONEDRIVE_SSH" ]; then
        ONEDRIVE_SSH="$HOME/OneDrive/ssh"
    fi
else
    # Linux (adjust if you mount via rclone/onedriver elsewhere)
    ONEDRIVE_SSH="$HOME/OneDrive/ssh"
fi

echo "Setting up SSH config from: $ONEDRIVE_SSH"

# 2. Ensure local .ssh exists with correct permissions
mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"

# 3. Create the local override file if it doesn't exist
touch "$HOME/.ssh/config_local"
chmod 600 "$HOME/.ssh/config_local"

# 4. Backup existing config if it exists (file or broken symlink)
if [ -e "$HOME/.ssh/config" ] || [ -L "$HOME/.ssh/config" ]; then
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_NAME="$HOME/.ssh/config.bak_$TIMESTAMP"
    echo "Warning: Existing config found. Backing up to: $BACKUP_NAME"
    mv "$HOME/.ssh/config" "$BACKUP_NAME"
fi

# 5. Strategy: copy instead of symlink on macOS to avoid SSH permission errors.
#
#    SSH rejects configs whose *resolved* path has loose permissions. OneDrive-
#    synced files are often 644 and may be owned by a system process, which
#    causes: "Bad owner or permissions on ~/.ssh/config"
#
#    Instead, we write a wrapper config that embeds the OneDrive content
#    directly (copy, not link). Local overrides go in ~/.ssh/config_local.

WRAPPER="$HOME/.ssh/config"

# Write header with Include for local overrides
cat > "$WRAPPER" <<'HEADER'
# Auto-generated by unix-setup.sh — do not edit manually.
# Edit the OneDrive source config, then re-run unix-setup.sh to refresh.

# --- Local overrides (machine-specific settings) ---
Include ~/.ssh/config_local

HEADER

# Append the OneDrive config content directly into the wrapper (copy, not link)
if [ -f "$ONEDRIVE_SSH/config" ]; then
    echo "# --- Synced from OneDrive ($ONEDRIVE_SSH/config) ---" >> "$WRAPPER"
    cat "$ONEDRIVE_SSH/config" >> "$WRAPPER"
    echo "Synced OneDrive SSH config into local config."
else
    echo "Warning: $ONEDRIVE_SSH/config not found."
    echo "# Add your SSH hosts here, or re-run unix-setup.sh after OneDrive syncs." >> "$WRAPPER"
fi

chmod 600 "$WRAPPER"

echo ""
echo "SSH config installed at: $WRAPPER"
echo ""
echo "Tip: To re-sync after editing the OneDrive config, simply re-run:"
echo "  bash $ONEDRIVE_SSH/unix-setup.sh"
echo ""
echo "Done! Test it by running: ssh -G any-host"
